// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/external-secrets/external-secrets/apis/externalsecrets/v1beta1

package v1beta1

// PushSecretData is an interface to allow using v1alpha1.PushSecretData content in Provider registered in v1beta1.
#PushSecretData: _

// PushSecretRemoteRef is an interface to allow using v1alpha1.PushSecretRemoteRef in Provider registered in v1beta1.
#PushSecretRemoteRef: _
