// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/mongodb/mongodb-kubernetes-operator/pkg/automationconfig

package automationconfig

#Topology: string // #enumTopology

#enumTopology:
	#ReplicaSetTopology

#ReplicaSetTopology:     #Topology & "ReplicaSet"
_#maxVotingMembers:      int & 7
_#arbitersStartingIndex: int & 100
