// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/mongodb/mongodb-kubernetes-operator/pkg/automationconfig

package automationconfig

#ConfigKey: "cluster-config.json"
