// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/stretchr/objx

package objx

#SignatureSeparator: "_"

#URLValuesSliceKeySuffixEmpty: ""
#URLValuesSliceKeySuffixArray: "[]"
#URLValuesSliceKeySuffixIndex: "[i]"
