// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/stretchr/objx

package objx

// MSIConvertable is an interface that defines methods for converting your
// custom types to a map[string]interface{} representation.
#MSIConvertable: _

// Map provides extended functionality for working with
// untyped data, in particular map[string]interface (msi).
#Map: {...}
