// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/mongodb/mongodb-kubernetes-operator/api/v1

// Package v1 contains API Schema definitions for the mongodbcommunity v1 API group
// +kubebuilder:object:generate=true
// +groupName=mongodbcommunity.mongodb.com
package v1
