// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/external-secrets/external-secrets/apis/generators/v1alpha1

// Package v1alpha1 contains resources for generators
// +kubebuilder:object:generate=true
// +groupName=generators.external-secrets.io
// +versionName=v1alpha1
package v1alpha1
