// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/external-secrets/external-secrets/apis/generators/v1alpha1

package v1alpha1

#Group:   "generators.external-secrets.io"
#Version: "v1alpha1"
