// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rabbitmq/cluster-operator/api/v1beta1

// Package v1beta1 contains API Schema definitions for the rabbitmq v1beta1 API group
// +kubebuilder:object:generate=true
// +groupName=rabbitmq.com
package v1beta1
